ddvug_willibald_samen:
  target: dev
  outputs:
    dev:
      account: '{{ env_var(''DWH_SNOWFLAKE_ACCOUNT'') }}'
      database: '{{ env_var(''DWH_DATABASE'',''DWS'') }}'
      password: '{{ env_var(''DWH_PASSWORD'') }}'
      role: ACCOUNTADMIN
      schema: DWH_02_LOAD
      threads: 6
      type: snowflake
      user: '{{ env_var(''DWH_USER'') }}'
      warehouse: compute_wh
