{% macro create_file_formats() %}

CREATE OR REPLACE FILE FORMAT DWS.DWH_01_EXT.FF_SEMICOLON
TYPE = CSV
FIELD_DELIMITER =';'
SKIP_HEADER=1
EMPTY_FIELD_AS_NULL =TRUE
;
CREATE OR REPLACE FILE FORMAT  DWS.DWH_01_EXT.FF_SEMICOLON_WO_HEADER
TYPE = CSV
FIELD_DELIMITER =';'
SKIP_HEADER=0
EMPTY_FIELD_AS_NULL =TRUE
;

{% endmacro %}
